# Top-level configuration
name = "svelte-cloudflare-template"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration for SvelteKit
[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

# Build configuration for SvelteKit
[build]
command = "npm install && npm run build"
